### PR TITLE
Generate PDF from AsciiDoc

### PR DESCRIPTION
**Pull request by monsieuremre**
Branch not ready to merge yet. Created for feedback.

The following are ready:
* Documentation in [readme](https://github.com/monsieuremre/aas-specs/blob/asciidoc_master/docs/README.md)
* The main outlines of the general [theme](https://github.com/monsieuremre/aas-specs/blob/asciidoc_master/docs/theme.yml)
* Setting the most apparent/obvious properties of the document

By outlines I mean I adjusted the font sizes, colors, borders, margins, spacing, background and indentation to directly mirror the original docx file.

Known problems are:
* Unfortunately Arial is not a bundled font in asciidoc-pdf. We fallback to Helvetica as the default font from the same font family, that is often used as a direct replacement.
* Adoc files are different from the original document. They lack for example the non-section titles like Impressum and Table of Contents. Therefore in the pdf, these lack titles. This should be resolved in the adoc file itself and not with theming.
* Title page is not really defined in the adoc file. This also causes problems. The first page is automatically the title page. Unfortunately the background image does not cover the whole page.
* Document title is also printed as text eventhough we already have it in the image.
* Overall, having the title page not defined as a proper titlepage but rather as an image causes many problems.
  * It is not possible to select text on an image title page.
  * It is also not possible to create dynamic links.
  * It also takes too much space.
  * It won't adjust for higher resolution screens and pixelate.
  
To solve this, a title page can be defined. Which it already is, and commented out. This would solve all the problems and result in more reproducable and better pdf documents. The only downside would be, it would resemble a little less to the original word document. Please provide feedback as to how I should proceed regarding the title page. That is, should I necessarily find a solution with the image or go with a new text based title page.

Other than that, there are probably other details that you would like to be addressed @zrgt. Please review the produced [PDF](https://github.com/monsieuremre/aas-specs/blob/asciidoc_master/docs/AASiD/AASiD_1_Metamodel/IDTA-01001-3-0_SpecificationAssetAdministrationShell_Part1_Metamodel.pdf) and list what you think needs adjustment other than what I already mentioned.

### CODE REVIEW

**Comment by monsieuremre** [comment]
Fixed: Cover page image proportions and other mentioned problems.

There remains only one problem, and that is with the AASiD_2_API. It does not have the usual cover page defined in image1.png. There is a jpeg file instead, which does not contain the title and author information. To fix it, a png file should be added accordingly that reflects the word documents cover.

**Comment by monsieuremre** [comment]
PDF Files are added for all of them. Comment on what should be adjusted further and/or changed completely in the theming.

**Comment by monsieuremre** [comment]
> To fix it, a png file should be added accordingly that reflects the word documents cover.

Should I proceed to adding this image file manually or should this be handled by a script?

**Comment by zrgt** [comment]
> > To fix it, a png file should be added accordingly that reflects the word documents cover.
> 
> Should I proceed to adding this image file manually or should this be handled by a script?

You can do it manually

**Comment by zrgt** [comment]
- [x] @monsieuremre please find out if you can define the style of header rows and columns of tables, such that they have a blue background. For the reference see the word document. If it is possible please define the style.

When this is done, we can set the issue on hold, as we have one other issue with higher priority. I will discuss it with you on friday.

**Comment by monsieuremre** [comment]
> @monsieuremre please find out if you can define the style of header rows and columns of tables, such that they have a blue background. For the reference see the word document. If it is possible please define the style.

Done.

For the second pdf, there is still no cover page. I tried manually adding this, and the problem persists. The reason for this is, there is no cover page in the images folder. When I try to manually extract all the images from the word file, I get the exact same set of images. This is a problem with the word file. The cover page is not a single image that extracts out normally, unlike all the other word files. This specific one needs fixing in the word document so the cover is an image, or an image should be created for the cover seperately.

Other than that, everything you mentioned is fixed.

**Review by zrgt — CHANGES_REQUESTED** [review]
@monsieuremre Great job, thank you! 

- [ ] Can you find out if it is possible to define in pdf theme, that specific tables of class `table-with-appendix-table` do not have bottom-margin. Similliar as realized in style.css: https://github.com/rwth-iat/aas-specs/blob/3df2b70c5e81eb3c6bbf7761919cf37f07f4339c/docs/style.css#L55
- [ ] Fill the cover page 100% with the cover image

**Comment by monsieuremre** [comment]
>  Can you find out if it is possible to define in pdf theme, that specific tables of class table-with-appendix-table do not have bottom-margin. Similliar as realized in style.css: 

I have tried many ways and did research. I can say with certainty that, unfortunately it is not possible to define in the theming for just the specific type. There is a way to remove bottom margins for all blocks at once, but different margins per block is not yet possible. See [here](https://github.com/asciidoctor/asciidoctor-pdf/issues/2011#issuecomment-1068440812).

>  Fill the cover page 100% with the cover image

It already does cover the whole page. Only the second one lacks a cover page, which already fixed manually by adding a cover image and now it has a cover too. I created the cover image myself for this specific one, and for this reason it has no invisible margins. But the same can't be said about the pre-secisting covers.

If you are talking about the thin white lines at the borders, those are part of the images. You can examine any cover page image manually and you will observe that there is an invisible transparent margin at the borders. This can be fixed by either:
* manually fixing the cover images
* setting the background image as the same blue so the invisible borders become blue instead of white and they blend in

**Comment by zrgt** [comment]
Ok. We can keep he cover images. You don't have to fix them.

**Comment by zrgt** [comment]
@monsieuremre is the PR ready to merge?

**Comment by monsieuremre** [comment]
> @monsieuremre is the PR ready to merge?

Yes.

**Review by zrgt — APPROVED** [review]

**Pull request merged**
