### PR TITLE
 Transform the document IDTA-01003 to AsciiDoc

### PR DESCRIPTION
**Pull request by monsieuremre**
Transformed according to the guidelines. I have also run the scripts on the document. Although, image files do not seem to convert to png from emf in the media folder. Is this behavior expected?

### CODE REVIEW

**Comment by monsieuremre** [comment]
>  Is this behavior expected?

Apparently not. Created this [issue](https://github.com/admin-shell-io/word2asciidoc/issues/1) for image conversions. I will convert the images manually to png. I have done some testing and I can confirm I can 100% reproduce the script conversion. See the issue for more details.

Apart from that, did some manual fixing like adding the toc. If you could specifically point out what else needs manual fixing by maybe providing examples other than what is already mentioned in the readme, it would speed up the process by quite a bit.

**Comment by zrgt** [comment]
- Convert images from emf to png
- Replace inline image definitions `image:./media/image3.png[image,width=642,height=223]SOMETHING` with block definitions `image::./media/image3.png[image,width=642,height=223]SOMETHING`. If you want you can also add an appropriate script into https://github.com/rwth-iat/word2asciidoc
- Set bibliography part as bibliography: 
```
// Bibliography Section. It removes section numeration.
[bibliography]
== Bibliography
```
- Repair tables: some tables have a complex structure, where first n rows have a first column as header column and the n+1 row is a header row. Such solumns have to be splitted and the first table should be of a class `[.table-with-appendix-table]`. For a reference take a look into `IDTA-01001-3-0_SpecificationAssetAdministrationShell_Part1_Metamodel.adoc`
- Generate an HTML and look if you find any further bugs

**Comment by monsieuremre** [comment]
Converted all images manually. Also updated the readme of word2asciidoc to mention these limitations.

For the first two after this, I added the functionality to the scripts and ran it. If I got the idea of image block correctly, they all function perfectly. They do not need to be done manually anymore. I need confirmation that replacing all image inlines with image blocks is what we actually want, and the way my script handles it is desirable.

>Repair tables: some tables have a complex structure, where first n rows have a first column as header column and the n+1 row is a header row. Such solumns have to be splitted and the first table should be of a class [.table-with-appendix-table].

Unfortunately I do not understand what do you mean exactly. I need further explanation for the following two questions. If I get the idea, I am positive I can integrate this also in the scripts so that it does not need manual fixing anymore in the future.

* Exactly what condidions need to be met so that I can re-classify a table as [.table-with-appendix-table]?
* Exactly what condiditions are met to determine the split point in the table?

**Comment by monsieuremre** [comment]
pushed

**Pull request closed without merging**
